# Generated by Django 5.0.2 on 2024-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_encargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavadora', models.CharField(choices=[('Lavadora 1', 'Lavadora 1'), ('Lavadora 2', 'Lavadora 2'), ('Lavadora 3', 'Lavadora 3'), ('Lavadora 4', 'Lavadora 4'), ('Lavadora 5', 'Lavadora 5'), ('Lavadora 6', 'Lavadora 6'), ('Lavadora 7', 'Lavadora 7')], max_length=20)),
                ('motivo', models.CharField(choices=[('encargo', 'Encargo'), ('publico', 'Público en general'), ('mantenimiento', 'Mantenimiento'), ('error', 'Error')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
