# Generated by Django 5.0.2 on 2024-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_activacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='pos.producto')),
            ],
        ),
    ]
