# Generated by Django 5.0.2 on 2024-04-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='importe_total',
            field=models.CharField(max_length=100),
        ),
    ]
