# Generated by Django 5.0.2 on 2024-04-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_venta_importe_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('productos', models.CharField(max_length=1000)),
                ('importe_total', models.CharField(max_length=100)),
                ('fecha_venta', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(),
        ),
    ]
