# Generated by Django 5.0.2 on 2024-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_ventas_importe_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='importe_total',
            field=models.CharField(max_length=100),
        ),
    ]
