# Generated by Django 5.0.2 on 2024-04-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_ventas_importe_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
