# Generated by Django 5.0.2 on 2024-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_ventas_importe_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='activacion',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='encargo',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ventas',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
