# Generated by Django 5.0.2 on 2024-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_delete_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargo',
            old_name='adeudo',
            new_name='anticipo',
        ),
    ]
