# Generated by Django 5.0.2 on 2024-04-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_rename_adeudo_encargo_anticipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargo',
            old_name='anticipo',
            new_name='adeudo',
        ),
    ]
