# Generated by Django 5.0.2 on 2024-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_rename_anticipo_encargo_adeudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('ENCARGO', 'Encargo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado')], default='ENCARGO', max_length=20),
        ),
    ]
