# Generated by Django 5.0.2 on 2024-05-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_alter_encargo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPagoEncargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encargo', models.DateField()),
                ('pago_recibido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adeudo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('encargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.encargo')),
            ],
        ),
    ]
