# Generated by Django 5.0.2 on 2024-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_controlpagoencargos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoFinalDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
