# Generated by Django 5.0.2 on 2024-06-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_saldofinaldiario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
