# Generated by Django 5.0.2 on 2024-06-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_producto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='activacion',
            name='encargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.encargo'),
        ),
    ]
