# Generated by Django 5.0.7 on 2024-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_activacion_encargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('ENCARGO', 'Encargo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='ENCARGO', max_length=20),
        ),
    ]
