# Generated by Django 5.0.7 on 2024-07-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_activacion_encargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='encargo',
            name='pagado',
        ),
        migrations.AddField(
            model_name='encargo',
            name='Folio',
            field=models.CharField(default='20240731', max_length=30),
        ),
        migrations.AddField(
            model_name='encargo',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('ENCARGO', 'Encargo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='ENCARGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='fecha_encargo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
