# Generated by Django 5.0.7 on 2024-07-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_encargo_entregado_alter_encargo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargo',
            name='entregado',
        ),
    ]
