# Generated by Django 5.0.7 on 2024-08-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_encargo_ingreso_alter_encargo_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargo',
            name='ingreso',
        ),
    ]
