# Generated by Django 5.0.7 on 2024-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_remove_encargo_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
