# Generated by Django 5.0.7 on 2024-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_remove_encargo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='ingreso',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=10),
            preserve_default=False,
        ),
    ]
