# Generated by Django 5.0.7 on 2024-07-30 23:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_encargo_entregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo_Control',
            fields=[
                ('Folio', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('fecha_encargo', models.DateField(default=datetime.date(2024, 7, 30), editable=False)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('ENCARGO', 'Encargo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='ENCARGO', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adeudo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
