# Generated by Django 5.0.7 on 2024-08-06 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_encargo_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos.cliente'),
        ),
        migrations.AddField(
            model_name='encargo',
            name='observaciones',
            field=models.TextField(default='Entrabajo'),
        ),
    ]
