# Generated by Django 5.0.7 on 2024-08-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_encargo_cliente_encargo_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
