# Generated by Django 5.0.2 on 2024-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_alter_encargo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
