# Generated by Django 5.0.7 on 2024-08-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_ventas_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('ENCARGO', 'Encargo'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ENTREGADO', 'Entregado')], default='ENCARGO', max_length=20),
        ),
    ]
