# Generated by Django 5.0.7 on 2024-08-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_encargo_forma_pago_lista_precios_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_precios',
            old_name='precio',
            new_name='Precio',
        ),
    ]
