# Generated by Django 5.0.7 on 2024-08-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_rename_precio_lista_precios_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargo',
            name='entregado',
        ),
    ]
