# Generated by Django 4.2.14 on 2024-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_remove_encargo_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=20),
        ),
    ]
