# Generated by Django 4.2.14 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_alter_ventas_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
