# Generated by Django 5.1.1 on 2024-10-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_alter_activacion_lavadora_alter_encargo_forma_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosencargos',
            old_name='encargo',
            new_name='encargoCompleto',
        ),
    ]
