# Generated by Django 5.1.1 on 2024-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_turnocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnocaja',
            name='ventas',
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='estado',
            field=models.CharField(default='abierta', max_length=10),
        ),
        migrations.AlterField(
            model_name='activacion',
            name='lavadora',
            field=models.CharField(choices=[('Lavadora 1', 'Lavadora 1'), ('Lavadora 2', 'Lavadora 2'), ('Lavadora 3', 'Lavadora 3'), ('Lavadora 4', 'Lavadora 4'), ('Lavadora 5', 'Lavadora 5'), ('Lavadora 6', 'Lavadora 6'), ('Lavadora 7', 'Lavadora 7'), ('Lavadora 8', 'Lavadora 8'), ('Lavadora 9', 'Lavadora 9'), ('Lavadora 10', 'Lavadora 10'), ('Secadora 1', 'Secadora 1'), ('Secadora 2', 'Secadora 2'), ('Secadora 3', 'Secadora 3'), ('Secadora 4', 'Secadora 4'), ('Secadora 5', 'Secadora 5'), ('Secadora 6', 'Secadora 6')], max_length=20),
        ),
    ]
