# Generated by Django 5.1.1 on 2024-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_remove_turnocaja_ventas_turnocaja_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpagoencargos',
            name='fecha_encargo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controlpagoencargos',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='fecha_encargo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pagosencargos',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='saldofinaldiario',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateTimeField(),
        ),
    ]
