# Generated by Django 5.1.1 on 2024-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0042_alter_controlpagoencargos_fecha_encargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='productos',
            field=models.CharField(max_length=10000),
        ),
    ]
