# Generated by Django 5.1.1 on 2024-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='productos',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
