# Generated by Django 5.1.1 on 2024-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0046_encargo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpagoencargos',
            name='forma_pago',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlpagoencargos',
            name='productos',
            field=models.CharField(default='Efectivo', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='productos',
            field=models.CharField(default='Efectivo', max_length=1000000, null=True),
        ),
    ]
