# Generated by Django 5.1.1 on 2024-12-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0047_controlpagoencargos_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpagoencargos',
            name='productos',
            field=models.CharField(default='Efectivo', max_length=1000000),
        ),
    ]
